[package]
authors = ["Philipp Korber <p.korber@1aim.com>"]
categories = []
description = "TODO"
documentation = "https://docs.rs/mail-codec-composition"
keywords = ["mail", "codec", "mime", "smtp"]
license = "MIT OR Apache-2.0"
name = "mail-codec-composition"
readme = "./README.md"
repository = "https://github.com/1aim/mail-codec-composition"
version = "0.1.0"


[dependencies]
futures = "0.1.14"
log = "0.3.8"
rand = "0.3.15"
scoped-tls = "0.1.0"
serde = "1.0.10"
serde_derive = "1.0.10"
vec1 = { git="https://github.com/1aim/vec1" }
total-order-multi-map = { git="https://github.com/1aim/total-order-multi-map" }
mail-codec = { git="https://github.com/1aim/mail-codec" }
mail-codec-core = { git="https://github.com/1aim/mail-codec-core" }
mail-codec-headers = { git="https://github.com/1aim/mail-codec-headers" }
error-chain = "0.11.0"
chrono = "0.4.0"
soft-ascii-string = "0.2.0"
futures-cpupool = { version = "0.1.5", optional = true }
tera = { version = "0.11.1", optional = true }
conduit-mime-types = { version = "0.7.3", optional = true}
lazy_static = { version = "1.0.0", optional = true }
tokio-smtp = { path="../depends/tokio-smtp", optional=true }
tokio-service = { version = "0.1", optional=true }
tokio-proto = { version = "0.1", optional=true }
# this is used by tokio-smtp, we need it to convert our Mailbox to their Mailbox struct
emailaddress = { version = "0.4", optional=true }

[dependencies.mime]
git="https://github.com/1aim/mime"
branch="parser_revamp"
version="0.4.0"


[dev-dependencies]
serde_json = "1.0.2"
regex = "0.2.6"
futures-cpupool="0.1.5"

[features]
debug_trace_tokens = []
render-template-engine = ["conduit-mime-types", "lazy_static"]
tera-bindings = ["tera", "render-template-engine"]
smtp = ['tokio-smtp', 'tokio-service', 'tokio-proto', 'emailaddress']
default = ["default_impl"]
default_impl = [
    "default_impl_name_composer", "default_impl_component_id", "default_impl_simple_context"
]
default_impl_name_composer = []
default_impl_component_id = []
default_impl_simple_context = [
    "default_impl_component_id", "mail-codec/default_impl_fs", "mail-codec/default_impl_cpupool"
]

traceing = [ "mail-codec/traceing" ]
